Resources:
  DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: 'Aurora PostgreSQL 10 Parameter Group'
      Family: aurora-postgresql10
      Parameters:
        rds.force_ssl: 1

  RDSSecurityGroupIngress:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DBSubnetGroup ${self:service}"
      SubnetIds:
        - !Ref SubnetAPublic
        - !Ref SubnetBPublic
        - !Ref SubnetCPublic

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'RDS Security Group'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - FromPort: 5432
          ToPort: 5432
          IpProtocol: tcp
          CidrIp: !GetAtt VPC.CidrBlock
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref 'AWS::StackName', rds]]

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: "${self:custom.rds.name}"
      MasterUsername: "${self:custom.rds.username}"
      MasterUserPassword: "${self:custom.rds.password}"
      DBClusterIdentifier: "rds-serverless"
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineVersion: 10.7
      EngineMode: serverless
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 2
        MaxCapacity: 16
        SecondsUntilAutoPause: 600
      DBSubnetGroupName: !Ref RDSSecurityGroupIngress
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
