Resources:
  DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: 'Aurora PostgreSQL 10 Parameter Group'
      Family: aurora-postgresql10
      Parameters:
        rds.force_ssl: 1

  AppSecurityGroupEgress:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      Description: 'permit PostgreSQL (5432) to DBSecurityGroup'
      DestinationSecurityGroupId: !Ref DBSecurityGroup
      FromPort: 5432
      GroupId: !GetAtt AppSecurityGroup.GroupId
      IpProtocol: tcp
      ToPort: 5432

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'RDS Security Group'
      SecurityGroupEgress:
        - Description: 'deny all outbound'
          IpProtocol: '-1'
          CidrIp: '127.0.0.1/32'
      SecurityGroupIngress:
        - Description: 'permit PostgreSQL (5432) from AppSecurityGroup'
          FromPort: 5432
          IpProtocol: tcp
          SourceSecurityGroupId: !GetAtt AppSecurityGroup.GroupId
          ToPort: 5432
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref 'AWS::StackName', rds]]
      VpcId: !Ref VPC

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: "${self:custom.rds.name}"
      MasterUsername: "${self:custom.rds.username}"
      MasterUserPassword: "${self:custom.rds.password}"
      DBClusterIdentifier: "rds-serverless"
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineVersion: 10.7
      EngineMode: serverless
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 2
        MaxCapacity: 8
        SecondsUntilAutoPause: 600
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
